### ISSUE TITLE
Example using typescript

### ISSUE THREAD

**Issue by johnjacobkenny** [anikait1/cowin-api-wrapper#1]
Could you share an example on using typescript?

I have installed as per the readme, but not getting the interfaces or types 
![image](https://user-images.githubusercontent.com/19240564/121199489-97a5bf80-c890-11eb-81dd-d25631c1b919.png)

Return type is any here 
![image](https://user-images.githubusercontent.com/19240564/121199583-af7d4380-c890-11eb-86c2-a805330442d0.png)

**Comment by anikait1** [comment]
Thanks for bringing the issue to my notice, I have updated the package and it should now work as intended. In case, you encounter any other issue, let me know!

**Comment by johnjacobkenny** [comment]
Yes the latest release fixes this issue, thank you!
