### ISSUE TITLE
Searching by week gives little to no output

### ISSUE THREAD

**Issue by johnjacobkenny** [anikait1/cowin-api-wrapper#2]
I am not sure whether this is an issue on the API side, or your code side. I didn't dig deeper into either.

```typescript
const data = await findAppointmentsByDistrict(districtId, {
    date: new Date(),
    week: true,
});
```

![image](https://user-images.githubusercontent.com/19240564/121272900-b635a600-c8e4-11eb-8e02-dfee9b5be145.png)

vs

```typescript
const data = await findAppointmentsByDistrict(districtId, {
    date: new Date(),
    week: false,
});
```

![image](https://user-images.githubusercontent.com/19240564/121273008-e715db00-c8e4-11eb-8113-b71bb227b422.png)

**Comment by anikait1** [comment]
It was an error on my behalf, I added an update to fix the same. Seems like adding tests in first place would have been a wise decision

**Comment by johnjacobkenny** [comment]
Great, thanks!
