### ISSUE TITLE
Disable cache for requests

### ISSUE THREAD

**Issue by johnjacobkenny** [anikait1/cowin-api-wrapper#3]
I'm not an expert on the concept of caching, but are cache modes like this possible so that this API always makes a fresh request for every request? Also is it possible to ask origin API to give latest data and not from cache?

References
https://stackoverflow.com/a/42518434/8323067
https://github.com/johntron/superagent-no-cache

**Comment by anikait1** [comment]
I have not implemented any caching mechanism, you can read about caching and throttling on the API page.

https://apisetu.gov.in/public/marketplace/api/cowin
